### ISSUE TITLE
Does not work in create-react-app

### ISSUE THREAD

**Issue by satazor** [pubkey/broadcast-channel#1]
<img width="565" alt="screen shot 2018-06-28 at 15 38 23" src="https://user-images.githubusercontent.com/1017236/42041225-59e404c4-7ae9-11e8-9406-fa9096f14deb.png">

It seems you are mixing import's and module.exports.

**Comment by pubkey** [comment]
@satazor thanks for reporting.
I fixed this and released a new version. Please test if everything is ok now.
