### ISSUE TITLE
Leader election race condition bug

### ISSUE THREAD

**Issue by Xesenix** [pubkey/broadcast-channel#10]
When opening a few tabs in same time few of them can get elected as leaders in parallel.

After further investigation i have noticed missing `responseTime` in type definitions here https://github.com/pubkey/broadcast-channel/blob/a3151d2922d25e04e33f526a568ba1f0c2f8a5d7/leader-election/index.d.ts#L4

Setting up this one for something like 2000-3000 fixes my case maybe worth adding some documentation for it.

**Comment by pubkey** [comment]
Which browser, which device?

**Comment by Xesenix** [comment]
Chrome 71.0.3578.98 Windows 10

Here PR with some missing types:
https://github.com/pubkey/broadcast-channel/pull/11

**Comment by pubkey** [comment]
I'm closing this. I think the defaults are ok for most users and now with your commit, others can learn how to make the election more reliable.
