### ISSUE TITLE
README.md test section update recommendation

### ISSUE THREAD

**Issue by steven87vt** [pubkey/broadcast-channel#12]
Hey thanks for the awesome lib! This was my answer to getting BroadcastChannel working in jest tests with vue. Just wanted to point out that in the test setup recommendations its states to `await BroadcastChannel.clearNodeFolder()` and technically you cannot await outside of an async function.

If you want to do this in say `beforeEach()` or `beforeAll()` in jest you have to use an await async wrapper before the tests execute or the newer builtin await syntax for jest `beforeEach(async () => { await BroadcastChannel.clearNodeFolder() })` [Jest#AddAsyncBeforeEach](https://github.com/facebook/jest/pull/1546)

**Comment by pubkey** [comment]
Hi @steven87vt 
can you make a PR with the change you propose?
The documentation assumes basic nodeJs skills, so I do not know if we should tell the user that `await` cannot be used in the root-scope.

**Comment by steven87vt** [comment]
Merged in #13
