### ISSUE TITLE
onmessage handler not invoked

### ISSUE THREAD

**Issue by steven87vt** [pubkey/broadcast-channel#15]
Hello @pubkey,

Wondering if its me or if there is an issue somewhere in the library where the `onmessage` handler is not invoked. I suspect its me and if it is I would really appreciate some guidance on what I am doing wrong.

I updated a previous sample you worked on. This sample shows that running either on node via jest or in the browser I cant seem to get the onmessage handler to print to the console. The reproduction code can be found here:

https://github.com/steven87vt/broadcast-channel-jest-fails-exit

Steps to reproduce in chrome, ie edge, ff:

1. Clone the above repo
2. Execute: `npm install`
3. Execute: `npm run build:dev`
4. Execute: `npm run start:dev`
5. Once the app starts navigate to localhost:8080, you should see the app load a test page where you can enter some text. 
6. Open your preferred debugger, set breakpoints in `home-page.vue#created()` hook and observe the following assignments after refreshing the page.

```javascript
this.authChannel.onmessage = function (message) {
  console.log(message)
}

const handler = message => console.log('arrow function handler: ' + message)
this.authChannel.addEventListener('message', handler)
```
7. Set a breakpoint on line 61 of `home-page.vue`. Enter some text in the input field and hit enter. Observe the following line of code is executed:

```javascript
this.authChannel.postMessage(user)
```

8. Examine the console logs for any output of a message. As far as I have seen none of the console statements are executed.

Reproduce via Jest:
1. Assuming you ran install in step 2 from above execute: `npm run test`

In `home-page.spec.js` I added a bunch of `await flushPromise()` and `await new Promise(...)` with `setTimeout()` hoping to diagnose if it was a node specific file system timing issue but I am seeing the same behavior in chrome, ie edge, and ff. In either test case nothing is ever logged in the console and in the 2nd test case the object method callback spy is never called.

I see that `onmessage` has a setter and that the setter updates the _onML array. The `addEventListener` function also updates the array. However after `postMessage` neither message handlers are invoked, or at least the debuggers are not stopping in them and `console.log()` has no effect.

I added a vscode launch settings file so you can debug the jest file in vscode if you like.

**Comment by pubkey** [comment]
When you click `Test BroadcastChannel` [here](https://pubkey.github.io/broadcast-channel/) does it work?

**Comment by steven87vt** [comment]
Seems so.

![image](https://user-images.githubusercontent.com/18038800/54711824-32374e00-4b21-11e9-9cb8-145211f2cc13.png)

**Comment by pubkey** [comment]
Can you try to create a PR with a test that reproduces your problem?

**Comment by steven87vt** [comment]
So I was not able to reproduce by modifying the simple test. In that
context it works fine. Which makes me wonder if it's not related to the vue
lifecycles. I'm going to mod my example tomorrow and see if setting
broadcast channel at the application root and accessing it via computed
getter would allow the on message handler to fire.

**Comment by steven87vt** [comment]
Another thing I noticed was if you set console.log to something undefined
it would error. When it's set to message it does nothing. Which might point
to a scoping issue.

**Comment by steven87vt** [comment]
If I am always in the same worker process being a SPA, would I ever be able to receive `onmessage` from the same thread that pushed `postMessage`?

**Comment by pubkey** [comment]
Yes but only if you create 2 channel instances. See [this](https://github.com/pubkey/broadcast-channel/blob/master/test/integration.test.js#L276) test

**Comment by steven87vt** [comment]
This is very likely the issue. I'll test when I get to work tomorrow and
let you know. Thanks for the support!!!

**Comment by steven87vt** [comment]
Thanks again @pubkey that was the problem. I pushed a new complete sample project that your free to use if you like. Ill leave it here so anyone else stumbling by this post has a reference to it: https://github.com/steven87vt/broadcast-channel-vue2-demo

As far as I know this is the only workaround for using broadcast spec in deployed production code as well as running unit tests on the js side via jest (which means node). Node does not support the broadcast channel spec. With this we are able to avoid environment/test related code in our production applications and develop our tests as if everything was normal. Thanks again for the awesome work on this!
