### ISSUE TITLE
Indexed Database repetead

### ISSUE THREAD

**Issue by lexfaraday** [pubkey/broadcast-channel#161]
I've found that the Indexed database from the Safari inspector appears multiple times the same idb, you can see this effect from the demo page too https://pubkey.github.io/broadcast-channel/e2e.html , do you know how can I prevent this?

Thanks!

**Comment by pubkey** [comment]
I have no apple products to reproduce this.
Can you post a screenshot from the safari inspector?
Also notice that the devtools often show outdated data because they clean up stuff way later then the actually delete happened.

**Comment by lexfaraday** [comment]
@pubkey Was just a bit strange because the data is duplicated at disk and the listener gets duplicated messages using Safari:

<img width="1609" alt="Screenshot 2020-04-16 at 18 43 14" src="https://user-images.githubusercontent.com/11020377/79483155-2c58b880-8012-11ea-9d34-4ef8d52c23e9.png">

<img width="1533" alt="Screenshot 2020-04-16 at 18 40 27" src="https://user-images.githubusercontent.com/11020377/79483044-f9162980-8011-11ea-87e2-82e4832c9621.png">

**Comment by pubkey** [comment]
This looks strange. Also that it is even possible that two tables with the same name exist.

**Comment by lexfaraday** [comment]
The problem is that my app receives the messages the same times as tables exists, If exists two tables with the same message I get the same message two times.

**Comment by lexfaraday** [comment]
Any way seems a specific bug for Safari not for this library, I close the issue, thanks for your support!!!

**Comment by pubkey** [comment]
I normally fix safari related bugs when possible, this is not the first one.
