### ISSUE TITLE
there are many such errors in nodejs

### ISSUE THREAD

**Issue by xxoo** [pubkey/broadcast-channel#176]
`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pubkey.bc\A406aabb9446fb6cd6dbd\messages\1588029990574025_w07frefudh_43jhfhsko5y.json'`

**Comment by pubkey** [comment]
I cannot reproduce this. Can you debug into it and check why this errors?
Maybe the foldername is too long.

**Comment by xxoo** [comment]
Sorry I've switched to postMessage since I read the document and it says this module is not suitable for dealing with over 50 messages per second in nodejs. And perhaps it has some kind of relation with this error.
