### ISSUE TITLE
Periodic errors on iOS

### ISSUE THREAD

**Issue by dartess** [pubkey/broadcast-channel#19]
I use the `redux-state-sync` package, which uses your package as a dependency.

I get bug reports from time to time:
```
TypeError
undefined is not an object (evaluating 't.id')
```
```
{snip} e(o)}})).then(function(t){return t.map(function(t){return t.id>e.lastCursorId&&(e.lastCursorId=t.id),t}).filter(function(t){return function( {snip}
```
https://github.com/pubkey/broadcast-channel/blob/master/src/methods/indexed-db.js#L227

Devices: iPhone, iPad.
Browser: Safari.
iOS versions: 12.1.1, 12.1.2, 12.2, 12.3.1.  

I do not know which package is causing the error, so I notified [both](https://github.com/AOHUA/redux-state-sync/issues/20).

**Comment by pubkey** [comment]
I do not think I can reproduce this on the given information.
The `msgObj` comes from `getMessagesHigherThen()` which should never return undefined, only objects.
Can you debug into this? Maybe my assumption is wrong ad a simple filter would fix this.

**Comment by dartess** [comment]
@pubkey Neither I nor the tester can reproduce the situation.
I only get reports from user devices. The error appears almost every day. If you have any ideas for collecting additional information that can determine the cause of the error, I can logs this information for a report.

**Comment by pubkey** [comment]
I added a check to filter out `undefined` msgObjects. I think this might fix the problem.

**Comment by dartess** [comment]
@pubkey 
![](https://i.gyazo.com/da0db1bc595f79bec3d3f9d13b5c8970.png)
After the update, the error disappeared.
Thank you for your work!
