### ISSUE TITLE
Leader elector isLeader always false in any tab

### ISSUE THREAD

**Issue by Dryymoon** [pubkey/broadcast-channel#21]
How to reproduce:

```
   import BroadcastChannel from 'broadcast-channel';
   import LeaderElection from 'broadcast-channel/leader-election';

   const channelName='SomeChannel';
   const channel = new BroadcastChannel(channelName, { webWorkerSupport: false });
   const tabElector = LeaderElection.create(channel);

   setInterval(() => console.log(tabElector.isLeader), 1 * 1000);
```

And in console always is tabElector.isLeader === false.

Browser: Chrome 75.0.3770.100

**Comment by pubkey** [comment]
Can you call awaitLeadership?
I think the leaderelectin is lazy

**Comment by Dryymoon** [comment]
> I think the leaderelectin is lazy
Yes, you right.
But after, for example 1 minute - single tab didn`t become leader.

**Comment by pubkey** [comment]
Please call `awaitLeadership()` to trigger the leader-election which will not start before.
If that does not help, please open a PR with a tests to reproduce.

**Comment by Dryymoon** [comment]
Adding call awaitLeadership() fix problem. Thx.

**Comment by pubkey** [comment]
Done this in the attached commit.
`isLeader` is not documented and meant for internal usage, so I added the lazy-info to the typings.
