### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by snaptopixel** [pubkey/broadcast-channel#22]
My browser is throwing the error mentioned due to this line:
https://github.com/pubkey/broadcast-channel/blob/master/src/method-chooser.js#L15

FWIW I'm using Rollup + StencilJS.

PR incoming 💣

**Comment by pubkey** [comment]
Can you reproduce the problem by changing the rollup config [here](https://github.com/pubkey/broadcast-channel/blob/master/config/rollup.config.js)?
Because this runs in the CI and if you can reproduce the problem there, we can ensure this never happens again.

**Comment by pubkey** [comment]
Closed, see here https://github.com/pubkey/broadcast-channel/pull/23#issuecomment-522129352
