### ISSUE TITLE
Listeners in originating page aren't called

### ISSUE THREAD

**Issue by snaptopixel** [pubkey/broadcast-channel#24]
If you use `addEventListener` in the page that originates the `postMessage` call they don't get called. Other pages are fine...

**Comment by pubkey** [comment]
I do not understand. Please add steps or code or a test to reproduce the problem.

**Comment by BilyachenkoOY** [comment]
I wouldn't expect to receive message which I send in the same tab, since I try to post data form _originating_ tab to all other pages, but not to myself

**Comment by pubkey** [comment]
An instance of BroadcastChannel does not recieve messages that was send by itself. This is equal to the behavior of window.BroadcastChannel.

**Comment by snaptopixel** [comment]
Agreed, sorry this was a bit of a knee-jerk reaction, I agree w/closing it. Thanks @BilyachenkoOY and @pubkey

**Comment by dumaron** [comment]
What @pubkey says is right, but I think that the explanation doesn't fully cover the problem. While it's true that an instance of a native `BroadcastChannel` does not fire when itself send a message, a scenario where more instances of `BroadcastChannel` lives in the same tab is possile, and the other instances in the same tab will react to the `postMessage()`.

For instance, one can have different distinct application, maybe made with different frameworks and living in the same tab (like me), and decide to use `BroadcastChannel` to communicate. With the native implementation this is possible, but seems to me impossible with this library.

Can this be considered a bug? This software wants to address this scenario or it's considered a non-goal?

**Comment by pubkey** [comment]
No this should work with this library. Creating multiple channels with the same name in a single javascript process will still send messages arround the channels.
