### ISSUE TITLE
Building Broadcast-Channel into vanilla Javascript?

### ISSUE THREAD

**Issue by 15kitscs** [pubkey/broadcast-channel#25]
Is it possible to build this module into vanilla javascript so that it can be used in applications that don't utilize nodejs? I've pulled down the package and it looks like it really meant to be used with nodejs.

**Comment by pubkey** [comment]
It already can be used wikthout nodejs.
Add a script-tag with this [file](https://github.com/pubkey/broadcast-channel/blob/master/dist/lib/browser.min.js) and then you can accesss `window.BroadcastChannel2`

**Comment by anup-khanal** [comment]
How do I use it in Vanilla Javascript? Do I copy the whole "lib" folder and then import browser.min.js?

**Comment by pubkey** [comment]
Import the min.js with a <script> tag

**Comment by anup-khanal** [comment]
so it handles all the fallback methods (like for IE or Safari BroadcastChannel does not work)? I see in the browser.js file that we do "require" does that mean we need those files too? or this is handled?

**Comment by anup-khanal** [comment]
btw thanks again! :)

**Comment by pubkey** [comment]
everything is included in [this](https://github.com/pubkey/broadcast-channel/blob/master/dist/lib/browser.min.js) file
