### ISSUE TITLE
Broadcasting across all Electron processes

### ISSUE THREAD

**Issue by lucasyvas** [pubkey/broadcast-channel#255]
In our setup, we are trying to import RxDB pointing at a `node-websql` file into the main process, as well as every renderer process in a preload (node-enabled) script.

We may be able to explore alternative configurations, however this was "simplest" for our current use case. This works absolutely great, except for the fact that changes made to the database in main do not trigger observables in the renderer, and vice versa.

I suspect I can probably help with this - based on what I've read so far, it seems all might be able to work if the node filesystem technique was used, or I could potentially contribute a new mechanism that works completely over Electron's IPC if that is favourable.

I'm looking for guidance around detection before jumping in though as it seems to be deliberately crafted the way it is now. Thanks.

**Comment by lucasyvas** [comment]
We did find a resolution! It might not satisfy everyone, but this will work:

```
const broadcastChannel = require('broadcast-channel')
broadcastChannel.enforceOptions({ type: "node" });
```

Since preload runs in a node context and so does main, this does the trick.

**Comment by pubkey** [comment]
Hm this should work out of the box. Did you create your database in the node-process? If yes, which type did the broadcast channel choose?

**Comment by lucasyvas** [comment]
We create the database in both main and renderer processes. We found that events didn't make it between the two, but didn't look too far into it.

Presumably the main process side would have used the node type, but I'm guessing the renderer side detected and used idb or something else. If I force the renderer to use the node channel it works.

The scenario was pointing at the same sqlite file from both processes.

**Comment by pubkey** [comment]
Are you using the electron remote api?
Bc as far as I understand the renderer process cannot use SQLite.

**Comment by lucasyvas** [comment]
The renderer process can use sqlite just fine over websql (the websql adapter is kind of not great, but that's not the issue).

As long as you import it and set it up in the renderer preload context, node will be available at that time then the rest of your renderer code can use it.

**Comment by pubkey** [comment]
@lucasyvas no you do not have to setup a project. I just want to find out if the behavior of RxDB is explainable or if this in non-intentional and should be fixed. Also I am still not sure if this is an edge case or not.

**Comment by pubkey** [comment]
I am closing this for now. I am using the broadcast-channel on electron and I think the behavior is correct.
If you find this problem please create a PR with a test to reproduce.
