### ISSUE TITLE
Not working on iPad safari

### ISSUE THREAD

**Issue by sriharsha566** [pubkey/broadcast-channel#258]

**Comment by pubkey** [comment]
What is not working?

**Comment by sriharsha566** [comment]
I am not receiving broadcast messages on iPad Safari

**Comment by pubkey** [comment]
Sorry but this question-answer ping pong is not worth the time.

**Comment by jpike88** [comment]
relevant information [https://caniuse.com/#search=broadcast](https://caniuse.com/#search=broadcast)

and frankly, if you're trying to use this on mobile safari, you should be releasing a proper app.
