### ISSUE TITLE
IE 11 Issue

### ISSUE THREAD

**Issue by 15kitscs** [pubkey/broadcast-channel#26]
I'm trying to use the vanilla javascript version of this module and I got the following error when I try to create a broadcast channel.  I get the following error:
Object doesn't support property or method 'find'
Here is the code that I'm using:
var Channel = new BroadcastChannel2("Channel");
According to the documentation, it doesn't say that you have to transpile the javascript for IE 11. Do you have transpile the javascript for all versions of IE? If so, is there a version fo the javascript that is already transpiled?

**Comment by pubkey** [comment]
it is transpiled for IE11. But it looks like you need polyfills. In your case, `Array.find()` is not known.
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill

**Comment by pubkey** [comment]
Can you open the test-page in your IE11 and check if that works for you?
https://pubkey.github.io/broadcast-channel/e2e.html
