### ISSUE TITLE
Stop opening multiple tabs

### ISSUE THREAD

**Issue by Neuroforge** [pubkey/broadcast-channel#273]
Hello,

I am trying to solve a specific problem and this api looks like it could be the way to go.

1) User opens a tab at the site and everything works great.
2) Second browser tab is opened on the same site, but i want to block this.

The user should only be able to open one tab. This is to avoid IndexDB and AWS Cognito issues that we are seeing.

I have tried....

1) Localstorage flags.
2) Cookie flags.
```

		(function ($) {
			var setCookie,
				removeCookie,
				// Create constants for things instead of having same string
				// in multiple places in code.
				COOKIE_NAME = 'TabOpen',
				SITE_WIDE_PATH = { path: '/' };

			setCookie = function () {
				$.cookie(COOKIE_NAME, '1', SITE_WIDE_PATH);
			};

			removeCookie = function () {
				$.removeCookie(COOKIE_NAME, SITE_WIDE_PATH);
			};

			// We don't need to wait for DOM ready to check the cookie
			if ($.cookie(COOKIE_NAME) === undefined) {
				setCookie();
				$(window).on('unload', removeCookie);
			} else {
				// Redirect to see-mode.com
				alert('Cannot open multiple See-Mode AVA tabs!');
				window.location = 'https://www.see-mode.com/';
			}
		})(jQuery);
```

Both of these approaches are flawed and can arrive at a situation where the website cannot be opened again. (Power loss/browser crash, flags are not unloaded, and user cannot get back to website as flags are permanently set).

So let's try the raw Broadcast API.

My first attempt is to use the raw BroadcastChannel API. 

```
    const channel = new BroadcastChannel('tab');

    channel.postMessage('another-tab');
    // note that listener is added after posting the message

    channel.addEventListener('message', (msg) => {
      if (msg.data === 'another-tab') {
        // message received from 2nd tab
        alert('Cannot open multiple instances');
      }
    });

```

This approach does not work as the message is sent to the first tab. We want the second tab to be stopped.

Is there a way for a new tab to know if there is already an elected leader tab exists already?

1) Tab 1 opens and is elected the leader.
2) Tab 2 opens, it is not the elected leader, so it alerts the user and redirects before init the app?

Thank you.

**Comment by pubkey** [comment]
You can call `applyOnce()` of the leader-elector and then check if the tab is the leader now. If not, another tab is the leader.
