### ISSUE TITLE
Unable to receive message at leader tab

### ISSUE THREAD

**Issue by maxim-fomin98** [pubkey/broadcast-channel#279]
Hello.

I faced trouble with receiving message to first tab, which is leader, from second, which was opened by first tab. At the beginning, I create channels, subscribe on receiving messages and create leader elector on first tab:

`this.myFirstChannel = new window.BroadcastChannel2("my-first-channel");`
`this.crmSoftphoneChannel.addEventListener("message", this.myFirstChannelMessageHandler);`
`this.mySecondChannel = new window.BroadcastChannel2("my-second-channel");`
`this.elector = createLeaderElection(this.mySecondChannel);`

Then I wait for message from second tab, in case of it is already opened, and if not, I open it. When second tab is closing, it sends message and first tab should receive it. But instead I get error in console on first tab:

![image](https://user-images.githubusercontent.com/66182662/89406496-ed1bb800-d725-11ea-80bf-d44bf6b5a21e.png)

Error occurs in function `_startListening(channel)`, when it tries to get listeners and iterate it with foreach `channel._addEL[msgObj.type].forEach`. The point is that msgObj.type is undefined, because msgObj is just my message (string).

What I do wrong?

Thank you.

**Comment by pubkey** [comment]
Can you try to create a PR with a test case to reproduce the problem?
