### ISSUE TITLE
Can you add in the options an array of Methods instead of OneOf

### ISSUE THREAD

**Issue by Moejoe90** [pubkey/broadcast-channel#29]
You have in the constructor some options. 
In the options i can provide a type `type?: MethodType,` This type will force one protocol for handeling alll broadcast messaging. 

Why not provide an array of types instead where i can specify the protocols i want to use and methods. I want to neglect for my case  `idb` and only want to use `["native","localstorage"]`. 

`idb` is very unstable for example as you can see here.
https://github.com/pubkey/broadcast-channel/issues/28

**Comment by pubkey** [comment]
If you set `webWorkerSupport: false`, the localstorage method will be prefered over idb.
Also you can call `canBeUsed()´ of each method an determine by yourself which method should be used.

**Comment by Moejoe90** [comment]
Ah this is good but not reffered to in the documentation. Can you give an example of how to use `canBeUsed`

**Comment by pubkey** [comment]
You can check if the native broadcastchannel can be used.

```js
const useMethod = window.BroadcastChannel ? 'native' : 'localstorage';
const myChannel = new BroadcastChannel('foobar', {
  type: useMethod
});
```
