### ISSUE TITLE
Jest reports TypeError: broadcast_channel_1.default is not a constructor

### ISSUE THREAD

**Issue by saucesome** [pubkey/broadcast-channel#33]
I'm importing broadcast-channel and everything is working great (thanks!). However, when writing tests, Jest is throwing an error:

`TypeError: broadcast_channel_1.default is not a constructor`

Any tips?

I'm importing BroadcastChannel like so:

`import BroadcastChannel from 'broadcast-channel';`

**Comment by pubkey** [comment]
Duplicate of #9
