### ISSUE TITLE
Communicating between different subdomains of a domain

### ISSUE THREAD

**Issue by santbob** [pubkey/broadcast-channel#333]
**Question**: Is it possible to communicate between two subdomains of a domain?
**Scenario**: I open a popup, which does some workup, upon completion, it should notify the window that opened the popup and pass data.

Since localStorage and BroadcastChannel are limited to the same-origin policy, was wondering if there are fallbacks handled in this lib?

**Comment by pubkey** [comment]
Not in this lib, sry.

**Comment by pubkey** [comment]
Maybe it works with cookies or postMessage() or via WebRTC
