### ISSUE TITLE
Changleog is missing

### ISSUE THREAD

**Issue by tmikoss** [pubkey/broadcast-channel#346]
This project does not appear to have a change log.

Please consider keeping a change log that outlines at least the breaking changes between versions. That would enable developers using this package to have easier time keeping up with the versions.

For example, I recently updated from 2.2 to 3.2. The change needed for my app was very minor, just restructuring the imports. However, tracking down what to do took considerably longer. The automated dependency upgrade PR just sat there for the longest time, tests failing and without any clear indication what to do to remedy the situation, waiting for a clear stretch of time for debugging. With clear description of changes I would have upgraded much earlier.

**Comment by pubkey** [comment]
Yes, sorry for that. I normally do not maintain a changelog for small projects. But broadcast-channel went a bit bigger then planned. I will add a changelog for future changes.

**Comment by tmikoss** [comment]
Thanks, looking forward for it!
