### ISSUE TITLE
many leaders

### ISSUE THREAD

**Issue by msotnikov** [pubkey/broadcast-channel#385]
Hello.

We use you great rxdb library in browser environment with couchdb live sync. But after some time more and more tabs becoming a leader. Therefore a lot live sync started many times. 

I think the problem in broadcast-channel library. Demo page after 5 minutes:
![scrnsht](https://user-images.githubusercontent.com/16710810/98002934-2c2dd800-1dff-11eb-8f4d-8a84b0f813bf.jpg)

**Comment by pubkey** [comment]
This is strange. Can you try if it also happens on firefox?
The most likely reason for duplicate leaders, is when the CPU is at 100% for a longer time.

**Comment by msotnikov** [comment]
> This is strange. Can you try if it also happens on firefox?
I'll try to reproduce.

> The most likely reason for duplicate leaders, is when the CPU is at 100% for a longer time.
Perhaps, in the end, only one leader remains (i don't known exactly what this library considers).
For the rxdb it looks like a lot of leaders and synchronization goes in many tabs. Perhaps adding an event on the loss of leadership would solve the problem (waitForLooseLedership)?

> From which browser+version are these screenshots?
Chrome 86.0.4240.111 (64 bit), Win10, core i7, 16ram

**Comment by pubkey** [comment]
The algorithm is designed to handle random exits of tabs or node processes.
When you close a browser tab or a node process dies, you cannot rely on it to send out a `waitForLooseLeadership` event. 
So the whole design is made to never having a running broadcast-channel loose leadership while still running, which makes everything less complex.

**Comment by msotnikov** [comment]
> When you close a browser tab or a node process dies, you cannot rely on it to send out a `waitForLooseLeadership` event.

I mean when tab still open. It possible case not only if tab dies.. Firefox more stable, but:

[
![Снимок экрана 2020-11-03 222647](https://user-images.githubusercontent.com/16710810/98031550-b4be6f80-1e23-11eb-8255-7dba25870d48.jpg)
](url)

**Comment by pubkey** [comment]
Ok this makes sense then. When the CPU is at 100%, the current leader cannot answer to the still-alive requests from the other tabs. Then they start electing a new leader. You can play with the params `fallbackInterval` and `responseTime` to increase the time and ensure you do not have multiple leaders. But this also slows down the initial leader election.

**Comment by msotnikov** [comment]
We already

**Comment by msotnikov** [comment]
I already set higher values. Not for demo, in our app with rxdb (I had to copy the leader-election plugin code).
```
fallbackInterval: 5000,
responseTime: 2000, 
```

Most users do not have powerful computers, it cannot be regulated and their activity is also not regulated. If this happens at least once, then a collapse begins (especially large in the case of synchronization and a large number of open tabs) without the possibility of programmatically determining, stopping and restoring normal operation.

**Comment by pubkey** [comment]
I tried to reproduce this.
I opened the example page in about 40 tabs and let it open while doing CPU heavy stuff.
How many cores does your system have?

**Comment by msotnikov** [comment]
> How many cores does your system have?
intel core i7 4558u # of Cores 2, # of Threads 4 


We also faced with this problem on Linux VM with 8 cores CPU Core i5

**Comment by msotnikov** [comment]
Thanks! But I can't check this fix right now.
