### ISSUE TITLE
LeaderElection example

### ISSUE THREAD

**Issue by gregmcguffey** [pubkey/broadcast-channel#393]
I do not understand how to use the Leader Election feature on a page that has other functionality. Wouldn't waiting for a promise block other code until the promise is resolved? My specific use case is trying to use this in a React component (functional component).  Is there an example how this is used on a page? I looked at the demo, but it didn't seem to work and I didn't see anything that looked like the code in the readme.

**Comment by gregmcguffey** [comment]
I actually figured out how to do this in react using a custom hook:

```javascript
import { useEffect, useRef, useState } from 'react';
import { BroadcastChannel, createLeaderElection } from 'broadcast-channel';

export default function useChannel(name, options) {
  const channel = useRef();
  const elector = useRef();
  const [isLeader, setIsLeader] = useState(false);

  useEffect(() => {
    if (!channel.current) {
      channel.current = new BroadcastChannel(name, options);
      elector.current = createLeaderElection(channel.current);
    }
  }, [name, options]);

  useEffect(() => {
    if (!isLeader && elector.current) {
      elector.current.awaitLeadership().then(() => {
        console.log('this tab is now leader');
        setIsLeader(true);
      });
    }
  }, [elector.current, isLeader, setIsLeader]);

  return [channel.current, isLeader];
}
```
A full example is at https://codesandbox.io/s/lucid-firefly-vxs22?file=/src/App.js

**Comment by pubkey** [comment]
Yes, looks correct.
Please update the docs if you find missing or confusing stuff.
