### ISSUE TITLE
Doesn't work in iframe page on Safari

### ISSUE THREAD

**Issue by woshiguabi** [pubkey/broadcast-channel#419]
I noticed that there are many issues about Safari, maybe because of this reason.

**Safari has disabled any cross-site message broadcast way through iframe, even if these iframe are same-origin and "prevent cross-site tracking" set to DISABLED**

https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

Example:
* module-a.foo.com
* module-b.foo.com
* account.foo.com

`module-a` and `module-b` have a `<iframe src="//account.foo.com" />`, `account` use `broadcast-channel` share data in same-origin iframe window (user, theme, i18n, etc...), then use `postMessage` sync parent window data. This is very commonly used in single sign-on. Everything is ok in other browsers.

I suggest pointing out this problem in the README to remind others to avoid this usage.

**Comment by woshiguabi** [comment]
https://codesandbox.io/s/safari-cross-site-jvmph

click "open in new window" and copy to another tab, tab1 can't connect with tab2

**Comment by pubkey** [comment]
Yes I can reproduce it with the [demo page in an iframe](https://7qp9w.csb.app/).
`SecurityError: IDBFactory.open() called in an invalid security context`

**Comment by pubkey** [comment]
We should add a "known problems" section to the docs which describes that.

**Comment by pubkey** [comment]
I'm closing this. PR is welcomed.
