### ISSUE TITLE
ES6 module

### ISSUE THREAD

**Issue by FirefighterBlu3** [pubkey/broadcast-channel#446]
Is there a build of this that works as a plain vanilla ES6 module, no nodejs? I'd like to incorporate this in my es6 modules, web workers, and service worker.

Trying to shoehorn the non-module or nodejs form seems to be very time intensive

**Comment by pubkey** [comment]
The normal build should work with plain browser javascript.
What is not working for you?

**Comment by FirefighterBlu3** [comment]
`browser.min.js` works only in foo.html.

`import { ... } from ...` doesn't work in an ESM/worker
`importScripts(...)` fails in a service worker

I have a considerable infrastructure in my modules and strongly prefer keeping things within it thus my desire to import and use directly within them. all this aside, i still need it to work in a service worker as well where there is neither `window` nor `this`

**Comment by pubkey** [comment]
I still not fully understand. Isn't [this](https://github.com/pubkey/broadcast-channel/blob/master/dist/es/index.js) a plain es6 module?
