### ISSUE TITLE
There is a way to call addEventListener with custom event type?

### ISSUE THREAD

**Issue by evperedadiaz** [pubkey/broadcast-channel#493]
I want to dispatch a custom Event type, but only have _postMessage()_ method with 'message' type.
How can I do it?

**Comment by evperedadiaz** [comment]
Maybe the intention is use a channel with only one type of Message(**T**).

**Comment by pubkey** [comment]
There is no official way to do this. The user is expected to send 'message' events.
You can hack around that by copying and changing the internal `_post` function https://github.com/pubkey/broadcast-channel/blob/master/src/broadcast-channel.js#L153
