### ISSUE TITLE
Module not found when using import

### ISSUE THREAD

**Issue by gabrielcolombo** [pubkey/broadcast-channel#5]
Using import BroadcastChannel from '...' throws an error on the browser console stating "Could not find module 'broadcast-channel' from ..." (Using it as a dependency on Ember.js)

When trying it on Node, is states that "Cannot find module babel-runtime/helpers/typeof".

Node - v.10.11.0
Ember - v3.1

How can I proceed?

**Comment by pubkey** [comment]
Can you post the full code and the full stack-trace?

**Comment by gabrielcolombo** [comment]
Ember.js (Main purpose)

```javascript
import BroadcastChannel from 'broadcast-channel';

...

window.channel = new BroadcastChannel('app');
```

```javascript
loader.js:247 Uncaught Error: Could not find module `broadcast-channel` imported from `shx-core-frontend/initializers/application`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at resolveInitializer (index.js:34)
    at registerInitializers (index.js:47)
    at exports.default (index.js:28)
```

Node.js (Testing)

```js
const BroadcastChannel = require('broadcast-channel');

```
```js
module.js:550
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/typeof'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/usr//broad/node_modules/unload/dist/lib/index.js:7:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by pubkey** [comment]
The problem came from the `unload` subdependency. I released `2.1.4`, please update and reopen if this does not fix your problem.

**Comment by gabrielcolombo** [comment]
I believe I can't reopen the issue since you were the one who closed it.

The node problem was fixed but the import one still remains (ember).

**Comment by pubkey** [comment]
Hmm. I have no ember skills and do not think I can fix this. Please open another ticket and repost the stack-trace.

**Comment by gabrielcolombo** [comment]
Seems like its a bug on Ember's browserify implementation. Works fine on a vanilla project.
You can close this now, thank you.

**Comment by srounce** [comment]
I can report this is still an issue with 2.1.5. 

A couple of questions:

1. Why are you only incrementing the patch version regarding this matter? 
Fixing this bug has a very strong possibility of breaking workarounds to this issue. Consumers with patch range versions will likely have a nasty surprise when things suddenly work as they should.

2.
    1. Why are there two transpilation targets?
    2. Why is there a separate entrypoint for each target?

**Comment by gabrielcolombo** [comment]
Oh, by the way, I had to migrate the files manually inside our project and rewrite some of the implementation in order to get it to work.
The issue was fixed by removing the ".js" extension from the import statements - as in
```
import IndexeDbMethod from './methods/indexed-db.js';
```

**Comment by pubkey** [comment]
@srounce 
- I did not think about people having workarrounds for this. I thought they might be first create an issue here before doing some hacks. Also hacky monkeypatches should not be handled by major version increments.
- We have to compilation-targets, one for the es-module-syntax. One for the old require-syntax. This is common on most javascript-projects
- There is a different entrypoint for es5-syntax so people can d `const bc= require('broadcast-channel')` instead of `const bc= require('broadcast-channel').default`.

@gabrielcolombo So this looks more like a bug with ember than with the broadcast-channel. Browserify should handle the .js ending properly.

**Comment by gabrielcolombo** [comment]
@pubkey Yeah I believe it's something related to ember's browserify plugin, I just haven't had the time to revise it yet. I'll get it fixed and go back to using the original implementation as soon as possible.

**Comment by srounce** [comment]
@pubkey 

1. I see where you're coming from, even so, some responsibility must be taken for the current situation with respect to the fact that fixing this will break things. 

2 & 3. You don't need any of this, I will have a look and hopefully send a PR.
