### ISSUE TITLE
Feature Request: Notify followers when leader is found.

### ISSUE THREAD

**Issue by CuddleBunny** [pubkey/broadcast-channel#506]
I was hoping to use a broadcast channel to prevent users from opening multiple tabs of my application. When I noticed the leader election feature of this library I got excited, hoping I could just use that. A naive psuedocode implementation would be something like:

```js
const elector = createLeaderElection(channel, {
  fallbackInterval: 2000,
  responseTime: 1000,
});

elector.awaitLeadership().then(() => hideNotLeaderModal());

setTimeout(() => showNotLeaderModal(), 1100);
```

By setting a timeout exceeding the leader election response time I'm hoping to avoid the modal flashing on the leader's screen but a cleaner approach could be achieved if followers were notified when each election is complete that another leader was found. This way I could guarantee that only followers would show the modal. Thoughts?

**Comment by pubkey** [comment]
Yes this makes sense. We should add an evenhandler for that. PR is welcomed.

**Comment by pubkey** [comment]
You can hack this by listening to the internal events of the broadcast channel like we do [here](https://github.com/pubkey/broadcast-channel/blob/master/src/leader-election.js#L198)
