### ISSUE TITLE
Are localStorage transfers ever cleaned up?

### ISSUE THREAD

**Issue by devinrhode2** [pubkey/broadcast-channel#522]
I was just reading the code here: https://github.com/pubkey/broadcast-channel/blob/14fb4256a3e6aa6562a5ecd7ae72bcde2aee3402/src/methods/localstorage.js#L65
And it looks like localStorage writes are never cleaned up.

I would suggest using this snippet:
```js
  localStorage.setItem(signalKey, payload)
  const cleanup = () => localStorage.removeItem(signalKey)
  document.addEventListener('visibilitychange', cleanup)
  setTimeout(() => {
    cleanup()
    document.removeEventListener('visibilitychange', cleanup)
  }, 1000)
  ```
visibilitychange has very very wide support these days, down to ie10 and old versions of mobile safari. Just be sure to use `document.` and not `window.`.

**Comment by pubkey** [comment]
No they never clean up atm. But every write uses the same key per channel. So there should always be only one localstorage item per channel.
I am not sure about using visibilitychange. Either we should use it on all browser methods or none, for example we do not use it at [indexeddb](https://github.com/pubkey/broadcast-channel/blob/14fb4256a3e6aa6562a5ecd7ae72bcde2aee3402/src/methods/indexed-db.js#L135)
What are the benefits of using it here? As far as I understand, setTimeout will always run but the timeout-time can be increased if the tab is not focus, which should not be a problem for running the cleanup.
