### ISSUE TITLE
Check if channel is closed

### ISSUE THREAD

**Issue by Niks218** [pubkey/broadcast-channel#544]
Hi, thanks for great library. Is there any options to check is channel is closed? I've stumbled across the issue that I'm trying to post to closed channel and it's not easy to manage channel's state. I saw in code, that you have flag to determine is it closed or no. Maybe, it would be good to expose it?

**Comment by pubkey** [comment]
Yes we can expose it. Please make a PR.

**Comment by Niks218** [comment]
@pubkey I submitted PR. Hope it's done properly
