### ISSUE TITLE
Nondeterministic Date handling

### ISSUE THREAD

**Issue by mattrussell-sonocent** [pubkey/broadcast-channel#561]
## Case
(Possibly) a bug.

## Issue

Below is a test which passes for me roughly 50% of the time, and 50% fails - that is, the `Date` is converted to a `String` 50% of the time. If I set `type: 'simulate'`, it works consistently, which is great. Should it be nondeterministic otherwise, though?

## Info
  - Environment: Node v12.9.1
  - Stack: Create React App w/ TypeScript

## Code

```ts
import { BroadcastChannel, enforceOptions } from 'broadcast-channel'

// beforeAll(() => enforceOptions({ type: 'simulate' }))

test('date serialisation', async () => {
  const channel1 = new BroadcastChannel<any>('dates')
  const channel2 = new BroadcastChannel<any>('dates')
  const isDate = (date: any): boolean => typeof date.getMonth === 'function'
  let resolveFn: any
  const promise = new Promise((resolve) => (resolveFn = resolve))
  channel2.onmessage = ({ date }) => resolveFn(isDate(date))
  const date = new Date('2000-01-01T15:30:00.00Z')
  await channel1.postMessage({ date })
  expect(await promise).toBe(true)
})
```

**Comment by pubkey** [comment]
Hi @mattrussell-sonocent 
sorry for the late answer. Can you make a PR with your test case? I can then start trying to fix it.

**Comment by pubkey** [comment]
Ah, btw you can only send data that can be JSON.stringify-ed. See https://github.com/pubkey/broadcast-channel#what-this-is-not

**Comment by mattrussell-sonocent** [comment]
Ah, OK, so while the browser Broadcast Channel API can transfer `Date`s, `broadcast-channel` library doesn't support it, is that right?

**Comment by pubkey** [comment]
yes this is right. I think we should add a JSON.parse to the the simulate-method to ensure everything is parseable and throw an error if not.

**Comment by mattrussell-sonocent** [comment]
Perhaps a bit off-topic for this ticket, but would `broadcast-channel` ever consider an option that, if enabled, would allow it to support more of the data types that are transmissible over the browser Broadcast Channel API? It would then I guess involve a serialisation-deserialisation step to support sending `Date` and other types that could reasonably be encoded in JSON (https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)

**Comment by pubkey** [comment]
I am not sure if this can work. Depending on which method is used, the module has to store the data as plain string very often.
You cannot store these datatypes in indexeddb for example.

**Comment by mattrussell-sonocent** [comment]
I was thinking something along the lines of: when using the Broadcast Channel API compatibility mode, the library could convert `Date`s and so on into pure JSON-serialisable values (e.g. `{ "__bcDate__": "2021-04-19T13:11:51Z" }`, or some such encoding scheme), and then back into `Date` the other end.

**Comment by pubkey** [comment]
This sounds quite complex and anyway would only work for dates.
What should happen when the property `__bcDate__` is already in use?

**Comment by mattrussell-sonocent** [comment]
> would only work for dates.

You could do `Map`, `Set`, `Regexp`, `ArrayBuffer` as well, I think, but yeah, not possible to encode everything, not least because some JS contexts won't even have all the supported types available. The nice thing about the JSON-only rule at present is at least it's a fairly obvious rule of what's meant to be supported and what isn't.

> What should happen when the property `__bcDate__` is already in use?

There's a choice for this sort of thing between encoding it so that it's fully reversible for any input (which is doable), or between saying that it's OK because no-one in practice will ever use the obscure property, provided you pick a sufficiently unusual enough name no-one will accidentally choose it!

**Comment by pubkey** [comment]
Sorry but this sounds like something I do not want to maintain.
I will stay on the JSON.stringify-able data only.
You might want to fork this project and later we can merge it back when it is proven that this works relyable.
