### ISSUE TITLE
`npm install` fails with npm 7

### ISSUE THREAD

**Issue by benmccann** [pubkey/broadcast-channel#604]
## Case
Bug

## Issue

There are numerous issues:
* relies on a plugin that has been removed: https://github.com/babel/babel/pull/6987
* uses `watchify` 4, but `karma-browserify` specifies that it is only compatible with `watchify` 3
* uses `rollup-plugin-uglify` which specifies that it is not compatible with Rollup 2

I'm not sure if there are others. You only see the next issue when the last one is fixed. I would personally suggest dropping Browserify and switching from Uglify to Terser.

## Info
  - Environment: Node 14.16.0 and npm 7.11.1

## Code

```sh
git clone git@github.com:pubkey/broadcast-channel.git
npm install
```

**Comment by pubkey** [comment]
@benmccann  is there anything more to do to fix this?

**Comment by benmccann** [comment]
Yes. I only fixed the first of the three bullets. The other two items remain. I don't intend to work on this at all. I don't use `broadcast-channel` at all myself, but just noticed this while trying to help someone use the library with SvelteKit

**Comment by pubkey** [comment]
Ok so I assume this is done for now since I am not using rollup.

**Comment by benmccann** [comment]
I'm not understanding. This isn't done and isn't related to Rollup at all. The issue is that I can't develop on this repo because when I check out the repo's code and run `npm install` it fails because npm 7 is stricter than npm 6

**Comment by pubkey** [comment]
You are right sry. Reopened.
