### ISSUE TITLE
ES version should not use `require`

### ISSUE THREAD

**Issue by benmccann** [pubkey/broadcast-channel#636]
## Case
Bug

## Issue

`dist/es/method-chooser.js` has a `require` call in it:

https://github.com/pubkey/broadcast-channel/blob/95f9b4d8a070ea61ea3246e46701179e1036cd77/src/method-chooser.js#L27

Using `require` is not valid ES code. The code should only use `import`

## Info
  - Environment: Node.js
  - Method: Vite 
  - Stack: SvelteKit

## Code

Simply run `npm install --save broadcast-channel` and you can see that `require` is used in `node_modules/broadcast-channel/dist/es/method-chooser.js`

Here's a codesandbox: https://codesandbox.io/s/svelte-query-bug-141-f0ksh

**Comment by vinayakkulkarni** [comment]
Yep, facing the same issue with Vue 3 + Rollup

**Comment by pubkey** [comment]
I have no idea how to implement this without the require-hack we currently use. Please make a PR if you have a plan.
Notice that is must work on browsers and nodejs and should not make bundler include the node-method into browser bundles.

**Comment by pubkey** [comment]
Closing this. PR with a proposal on how to fix is welcomed.

**Comment by benmccann** [comment]
What do you think about generating a separate ES build and Browserify build? Then you could use `sed` or a Babel replacement to swap out `require` for `import` in the ES build or you could delete everything in `isNode` for the Browserify build

**Comment by pubkey** [comment]
Yes this makes sense.
We could place a different package.json at the /browser folder. Then people could do
```ts
import { BroadcastChannel } from 'broadcast-channel/browser'
```

**Comment by benmccann** [comment]
We shouldn't need a separate `package.json`, but just need to specify the `browser` field in the existing `package.json`. I sent a PR for that as a first step: https://github.com/pubkey/broadcast-channel/pull/677

If that gets merged I can follow up shortly after to fix the `import` / `require` thing
