### ISSUE TITLE
Add or remove event listener should be based on a function id instead of the function itself

### ISSUE THREAD

**Issue by thaoxuanhoang** [pubkey/broadcast-channel#659]
## Case
Request for a new feature

## Issue
- `removeEventListener` matches the handler function passed into `addEventListener`
- This is not flexible as the 2 functions may be invoked from different places
- Could it be better to pass a `handlerId` into `addEventListener` to identify the handler?
- Then `removeEventHandler` can just accept a `handlerId` instead of a whole function

## Code

```js
  import { BroadcastChannel } from 'broadcast-channel';
  const channel = new BroadcastChannel('foobar');

  const handler = (message) => console.log(message);
  const handlerId = 'handler-id-1';

  // add event handler
  channel.addEventHandler('message', handlerId, handler);

  // remove the handler from a different file
  channel.removeEventHandler('message', handlerId);
```

**Comment by pubkey** [comment]
I want to stay as similar as possible to the official implementations. https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/message_event

**Comment by thaoxuanhoang** [comment]
I see your point.

I'd like to elaborate on use cases that it doesn't work nicely.

// A.ts
```javascript
import { BroadcastChannel } from 'broadcast-channel';

class A {
  private handler = (message: string) => console.log(message);

  subscribeToChannel = (): void => {
    const channel = new BroadcastChannel<string>('ChannelName');
    channel.addEventListener('message', this.handler);
  };

  unsubscribeFromChannel = (): void => {
    const channel = new BroadcastChannel<string>('ChannelName');
    channel.removeEventListener('message', this.handler);
  };
}

export default A;
```

// B.ts
```javascript
import A from './A';

const firstA = new A();
firstA.subscribeToChannel();
```

// C.ts
```javascript
import A from './A';

const secondA = new A();
secondA.subscribeToChannel(); // This will not work because `handler` is in a different instance
```

The work-around has to be making `handler` a singleton/global/modular function & import it into `A.ts`.

Another use case is that it's impossible for `handler` to unsubscribe itself if a certain message is received.

**Comment by pubkey** [comment]
I see the use case. But it is still trivial to implement an id-handler mapping with a few lines of code if needed.
I really prefer to stay with the 'standard' behavior of `addEventHandler`.
