### ISSUE TITLE
Cannot listen for error events

### ISSUE THREAD

**Issue by psalaets** [pubkey/broadcast-channel#68]
After reading through the [typescript defs](https://github.com/pubkey/broadcast-channel/blob/master/types/broadcast-channel.d.ts#L36) I tried this

```js
channel.addEventListener('error', error => {
  console.log(`error was ${error}`)
});
```
and it failed

```
Trace: TypeError: Cannot read property 'push' of undefined
    at _addListenerObject (.../broadcast-channel/dist/lib/broadcast-channel.js:204:24)
    at BroadcastChannel.addEventListener (.../broadcast-channel/dist/lib/broadcast-channel.js:134:5)
```

It seems that listening to error events isn't supported (https://github.com/pubkey/broadcast-channel/blob/master/src/broadcast-channel.js#L35), so maybe ts defs need to be updated?

Thanks for sharing this library

**Comment by pubkey** [comment]
I checked the code and have not found any emitting error-events.
Can you add a test-case where the subscribed error-stream actually emits something?

**Comment by pubkey** [comment]
Ah I misunderstood the problem. Got it now.
I think we should just remove the `error` from the typings.
The additional check at runtime increases the build-size of the module by 80b [see here](https://travis-ci.org/pubkey/broadcast-channel/jobs/615845183?utm_medium=notification&utm_source=github_status)

**Comment by psalaets** [comment]
> I think we should just remove the error from the typings.

I updated my PR accordingly

**Comment by pubkey** [comment]
Thank you I merged it.
I will publish a release in a few minutes
