### ISSUE TITLE
is offline communication supported?

### ISSUE THREAD

**Issue by asmallfurrywombat** [pubkey/broadcast-channel#7]
I brought up two pages running the demo using the latest version of Chrome (73.0.3639.1) on OSX. When the page were up, I unplugged the network connection and pressed "Test BroadcastChannel" but the send timed out. It worked well when the connection was plugged in. Perhaps it is something specific to the demo - does this project support offline communication?

**Comment by pubkey** [comment]
Yes, everything should work offline. What does your console say? The demo might break offline because it cannot load the workers js-file.
