### ISSUE TITLE
What changed from v3 to v4 to merrit a major version increment?

### ISSUE THREAD

**Issue by rfox12** [pubkey/broadcast-channel#707]
## Case
Request for documentation

## Issue
Major version change from 3.X.X to 4.X.X

## Info
I do not immediately see what changed.  Usually a major version change means that there are breaking changes.  The change log itself doesn't really help from an end-user perspective.  Documentation to help those migrating from v3 to v4 could be helpful.

**Comment by pubkey** [comment]
The exports in the package.json changed.
I increased to the next major version because it was too likely that things break for the users.
You can check the commits to see each change.

**Comment by rfox12** [comment]
Can you at least elaborate on what is likely to break?
