### ISSUE TITLE
es modules fail to load in browser (.js extension is required)

### ISSUE THREAD

**Issue by chase-moskal** [pubkey/broadcast-channel#721]
## Case
bug/enhancement

## Issue
hello. i tried to import from the esbrowser distribution, but since the imports in that distribtuiion don't have `.js` extensions, it doesn't work in browsers.

## Info
  - Environment: browser
  - Method: n/a
  - Stack: typescript

## Code

```js
import {BroadcastChannel} from "broadcast-channel/dist/esbrowser/index.js"
```

since browsers require `.js` extensions, but other environments (like bundlers or node) don't mind the extension, this issue can be resolved simply by adding `.js` extensions, and this will restore browser comaptibility without degrading compatibility elsewhere.

:tumbler_glass: cheers

**Comment by pubkey** [comment]
Can you make a PR with the proposed change?

**Comment by chase-moskal** [comment]
@pubkey probably not anytime soon, but this should probably be considered an open issue, if you intend the library to be compatible with browsers as we move into the future

in the meantime, i switched to another library as a temporary measure
