### ISSUE TITLE
Service worker do not support native anymore

### ISSUE THREAD

**Issue by reno1979** [pubkey/broadcast-channel#74]
since this has been added to the code: 

`/**
     * in the electron-renderer, isNode will be true even if we are in browser-context
     * so we also check if window is undefined
     */
    if (isNode && typeof window === 'undefined') return false;
`  

the service worker will never be able to use native

**Comment by pubkey** [comment]
The worker mode works in the test-page. see here https://pubkey.github.io/broadcast-channel/e2e.html

Please be more clear on the problem when you open tickets. Post code and stacktrace etc.
