### ISSUE TITLE
not stable work with worker-threads on node v14.15.0

### ISSUE THREAD

**Issue by Nau077** [pubkey/broadcast-channel#751]
## Case
BUG

## Issue
Sometimes (3-4 times from 10) I cant get message at worker-thread. No errors, no warnings, no anything. I have found simillar issue https://github.com/pubkey/broadcast-channel/issues/14#issuecomment-468350570 - but the advice at the ticket did not help me (to use setTimeOut with some seconds). 

Unfortunately I had to use native node.js  parentPort object  (require from worker_threads) at worker and use native worker.postMessage method at parentPort to make the app work. 
It is bad because I had to send worker-thread instance during several methods, and I thing I was happy if I could use broadcast-channel library.

## Info
  - Environment: (Node.js/browser/electron/etc..) node.js , node v14.15.0
  - Method:Node 
  - Stack: javascript

## Code

at main thread:
```js
at main thread:
  const { BroadcastChannel } = require("broadcast-channel");
  const bcChannel = new BroadcastChannel("someEvent", {
      type: "node"
  });

  bcChannel.postMessage({port: 100500});
  /* ... */
```
at worker-thread:
```js
  const { BroadcastChannel } = require("broadcast-channel");
  const bcChannel = new BroadcastChannel("someEvent", {
    type: "node"
  });

  bcChannel.onmessage = msg => {
    if (msg.port) {
       // some action
    }
  };

```

**Comment by pubkey** [comment]
Can you make a PR with a failing testcase?
