### ISSUE TITLE
BroadcastChannel using node method keeps tests from finishing

### ISSUE THREAD

**Issue by humphd** [pubkey/broadcast-channel#8]
I'm trying to use BroadcastChannel in my library, and it works great in the browser.  However, when I try to run my tests in node, where it uses the `node` method, my tests never complete (i.e, they all pass, but the `mocha` runner never exists).

I assume it's retaining open connections in order to facilitate the message channel.  I also assume calling `close()` on my channel would clean this up, but my code doesn't work that way (i.e., in a browser, killing the window is the cleanup vs. an explicit call).

Is there some way to work around this that I'm not seeing or understanding?

Thanks for this, library, by the way.  I had been looking for a replacement for https://github.com/diy/intercom.js/, and I think this is going to be perfect.

**Comment by pubkey** [comment]
I'm sorry but I do not think this is possible. The broadcast-channel on node will listen to a unix-socket which will never clear up the event-loop until the socket is closed.

**Comment by humphd** [comment]
OK, I wondered if that would be the case.  Thanks for confirming.

**Comment by steven87vt** [comment]
I have a similar problem in Jest, but I am actually calling .close() on the connection before the test exists and it still wont allow the test to exit. Is that still the expected behavior? Is there a way to programmatically stop the sockets?

**Comment by pubkey** [comment]
@steven87vt thanks for creating the demo-repo. This helps a lot.
It looks like jest does have a problem with `beforeDestroy` being async.
When I modify the code like the following, `timeout over` is never logged out.

```js
  async beforeDestroy () {
    if(this.authChannel) {
      console.log('# before destroy executing and closing authChannel')
      await new Promise(res => setTimeout(res, 100));
      console.log('timeout over');
      await this.authChannel.close();
    }
  }
```

**Comment by steven87vt** [comment]
Hey @pubkey thanks for the quick turn around. I added the destroy hooks to try and solve the issue with `.close()` but to no avail. I am not sure if this helps or points to the original issue you commented on:

> I'm sorry but I do not think this is possible. The broadcast-channel on node will listen to a unix-socket which will never clear up the event-loop until the socket is closed.

Before I put the destroy hooks in the vue `home-page.vue` component, which are forced during the unit test with `wrapper.destroy()`, that the Jest test would complete and hang while the `create()` hook was still processing `this.authChannel = new BroadcastChannel(options)` constructor. It seemed like the test jumped to completed and hung while awaiting the `promise.all()` block in the node method `ensureFoldersExist` function during the node method's `create()` function.

Not sure if that points to anything useful but I thought I'd mention it.

**Comment by pubkey** [comment]
@steven87vt 
I think your test-config has a problem with `wrapper.destroy()` being async.
When I modify the test like the following, all works.
```js
  test('login matches snapshot test.', async() => {
    const wrapper = createWrapper()
    expect(wrapper).toMatchSnapshot()
    wrapper.destroy()
    await new Promise(res => setTimeout(res, 1000))
  })
```
So I think you have to make sure that `wrapper.destroy` is awaited and the `beforeDestroy` is finished inside of it.

**Comment by steven87vt** [comment]
Yep that works! Thanks for your help.

**Comment by arielnmz** [comment]
I'm also experiencing this issue, my test is simpler though:

```
import BroadcastChannel from 'broadcast-channel'

class Foo {
  constructor() {
    this.bc = new BroadcastChannel.BroadcastChannel('test')
    this.bc.addEventListener('message', this.cb)
  }

  cb() {}
}

describe('Broadcast Channel', () => {
  beforeEach(async () => {
    await BroadcastChannel.clearNodeFolder()
  })

  test('local', async () => {
    // Create gmb instance
    const foo = new Foo()

    const result = await new Promise((a) => {
      setTimeout(() => {
        a(true)
      }, 1000)
    })

    expect(result).toBe(true)

    // Cleanup
    await foo.bc.close()
  })
})
```

But it still doesn't finish, am I missing something? I'm on Windows 10 using node lts/dubnium, jest 26 and broadcast-channel 3

**Comment by pubkey** [comment]
@arielnmz this should work. Can you PR a test so that the CI fails?

**Comment by arielnmz** [comment]
Sure
