### ISSUE TITLE
Console log in leader-election.js

### ISSUE THREAD

**Issue by jaunt** [pubkey/broadcast-channel#836]
Hello,

I generally turn off all logging in production except for errors.  Just wondering if this log statement in leader-election.js is required.  I'm getting it a lot in my console and without studying the code I'm not sure if this is normal or a warning condition because I'm using the module incorrectly:

```javascript
console.log('applyOnce via fallbackInterval');
```
P.s. thank you for this project, it's great!

**Comment by pubkey** [comment]
This was removed in the latest release yesterday.
