### ISSUE TITLE
Issue with beforeunload cancelation causing two leaders

### ISSUE THREAD

**Issue by telemmaite** [pubkey/broadcast-channel#85]
**I know it is kind of specific case.**
Our app opens two tabs (**A** and **B**) and only of them should become the leader so far everything is good.

The issue is when the user tries to close tab **A** our app uses the `beforeunload` event to show a pop up message 

> Are you sure?

at this stage, before any further action of the user tab **B** has become the leader. I guess because => https://github.com/pubkey/unload/blob/master/src/browser.js#L17

But unlike `unload` event, the `beforeunload`  does not mean the tab is 100% closed.

If the user confirms close of the tab all is fine, but if we chooses cancel then we end up with two leaders.

---
Not sure, but other option is if the tab appears as frozen during this browser/system popup which is triggering the election, though I still think it is manually on the `beforeunload` event.

**Comment by pubkey** [comment]
I do not think this edge case can be solved by this module.
The problem is that when you confirm-popups is open for a short time, the javascript process is blocked. This means that another tab will make itself leader event if the other tab keeps its leadership.

**Comment by telemmaite** [comment]
Fair enough. In case of cancel and the user not closing up the tab, this tab can never become a leader again and there is no proper way to catch the die/death event.

Very hacky but currently I wrap the `die()` just to get the event it was called and try to recreate a fresh elector by calling `createLeaderElection` and also I have to manually delete `channel._leaderElector`.

It would be nice if there was something like `awaitLeadership` but in way of `awaitDie` in that case if the dying **tab A** handled it\`s leadership(not closed) to **tab B** but then **tab B** got really closed, **tab A** has a chance to become once again a leader & get`s its crown back.
