### ISSUE TITLE
EMFILE: too many open files. When using this package in Layer0 platform.

### ISSUE THREAD

**Issue by jibin362** [pubkey/broadcast-channel#881]
![image](https://user-images.githubusercontent.com/69414163/152362129-b2498ad7-fcfc-4fae-a7f0-ee64ac46707f.png)

## Issue
Not sure if this is issue or my mistake. The following code is causing our production build to fail. The error seen is "EMFILE: too many open files".

Layer0 behind the screens runs their serverless codes using AWS lambda.

Can anybody point out why i may be facing such an issue. Is it due to my code issue or something else? All sort of help and comments welcomed.

_Note: Removing the package and related code resolved the issue._

## Info
  - Environment: Serverless, Layer0
  - Stack: Next.js, JavaScript

## Code

```js
  import { BroadcastChannel } from 'broadcast-channel';
  /** other react code **/
  const channel = React.useMemo(() => new BroadcastChannel('couldBeAnything'), [])

  useEffect(() => {
    const currentStore = Cookies.get('M2_country');
    channel.addEventListener('message', (msg) => {
      /** my function code **/
    })
    return () => {
      channel.close();
    }
  }, [])
```

**Comment by pubkey** [comment]
We need a PR with  a test case to reproduce this.
There is no way to debug your problem on the given information.

**Comment by jibin362** [comment]
Oh, seems I am not at the power to provide the full test case.

Basically, i only use this package to listen for the message event and do some action.

### Can you track how many channels your useMemo really opens?

Not sure to be frank. This issue seems to be only present in production site with traffic load.

Test and staging env works perfectly since we don't have load there.

Further question. Is there any dependency to backend server? As I understand from the package info, this is something that works only on the client side with no sync with backend.

**Comment by pubkey** [comment]
I do not thing there is a way to reproduce your problem with the given information.
