### ISSUE TITLE
BroadcastChannel is not a constructor

### ISSUE THREAD

**Issue by strarsis** [pubkey/broadcast-channel#9]
```js
    var channel = new BroadcastChannel('test');
    channel.postMessage('test');
````

During runtime:
````
Uncaught TypeError: BroadcastChannel is not a constructor
````
for the first line in the sample code above.

webpack 3.3 is used.

**Comment by pubkey** [comment]
How did you import the module?

**Comment by strarsis** [comment]
@pubkey:
```js
const BroadcastChannel = require('broadcast-channel');
````

**Comment by pubkey** [comment]
Hmm, that should work. Can you make a `console.dir(BroadcastChannel)` and paste the output?

**Comment by strarsis** [comment]
````
Object
  default: ƒ BroadcastChannel(name, options)
  __esModule: true
  __proto__: Object
````

**Comment by pubkey** [comment]
Hm. There is something wrong with your webpack-config (or with this module).
I think `import BroadcastChannel from 'broadcast-channel';` should work for you.

**Comment by strarsis** [comment]
Using `import` instead of `require` works.

**Comment by deiu** [comment]
Hi, I'm running into the same same issue. The output of `console.dir()` is the same as above. I can't switch to using `import` instead of `require` as it breaks other modules --> `Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`. BTW, webpack builds correctly. Here is my config:

```JavaScript
module.exports = {
  entry: './src/index.js',
  target: 'web',
  devtool: 'source-map',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'my-lib.js',
    library: 'myLib',
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
  node: {
    fs: 'empty'
  }
}
```

Any thoughts?

**Comment by deiu** [comment]
After digging a bit more, I found the solution. When using require to import ES6 modules, I need to access the `default` property:

```JavaScript
const BroadcastChannel = require('broadcast-channel').default
```

**Comment by kwerle** [comment]
This bit me, too.
```
const BroadcastChannel = require('broadcast-channel').default
```
did the trick.

Ugh.  JS.

**Comment by pubkey** [comment]
I'm sorry

**Comment by kwerle** [comment]
> I'm sorry

OK, maybe a step back is in order.  @pubkey , thank you so much for this!  Works like a charm once past this minor hurdle with a workaround.  I honestly don't know if there is a transparent fix for this 'issue', but if not, a simple note in the docs on the front page ought to do it.

You rock!

**Comment by pubkey** [comment]
My problem is that javascript require/modules are complex. This module is using a hachk and I am not sure if that is the best fix for the problem

**Comment by Moejoe90** [comment]
why not remove the default import and just have it be imported explicitly

**Comment by pubkey** [comment]
@Moejoe90 in the last release I removed the default export which should prevent this

**Comment by kxckingTimm** [comment]
i have the same problem but in my error the problem is the following:
const exchangeChannel = new BroadcastChannel('exchange');
                        ^

TypeError: BroadcastChannel is not a constructor

**Comment by azoulaynoam** [comment]
> 
Have you find a solution?

**Comment by azoulaynoam** [comment]
> i have the same problem but in my error the problem is the following: const exchangeChannel = new BroadcastChannel('exchange');
> 
> > ```
> >                     ^
> > ```
> 
> TypeError: BroadcastChannel is not a constructor

Have you find a solution?

**Comment by strarsis** [comment]
Hadn't tried again yet with a newer release. As this is potentially useful for a new project I will probably find it out soon.

**Comment by DenisVoloshin** [comment]
try to import it as

const { BroadcastChannel } = require('broadcast-channel');
const exchangeChannel = new BroadcastChannel('exchange');
