### ISSUE TITLE
nano-time in dependencies has no license file

### ISSUE THREAD

**Issue by kk-zu** [pubkey/broadcast-channel#920]
## Case
REQUEST

## Issue
`nano-time` in dependencies has no license file. I guess `nano-time` is not maintained. So it should be changed other package, for example,  https://www.npmjs.com/package/microtime
Thank you.

## Info
https://github.com/sazze/node-nanotime

## Code

```json
"nano-time": "1.0.0",
```

**Comment by pubkey** [comment]
Please make a PR
